#!/bin/bash

disEnable(){
    isDisabled="$(xinput --list-props $1 | awk '/Device Enabled/{print !$NF}')"
    if [ $isDisabled -eq 1 ]
    then
	xinput enable $1
    else
	xinput disable $1
    fi  
}

#Replace Elan TouchScreen, Elan Touchpad with the correct names of the devices
idTouchScreen="$(xinput --list --id-only 'ELAN Touchscreen')"
idTouchPad="$(xinput --list --id-only 'ELAN1200:00 04F3:301A Touchpad')"

[ $1 == "touchpad" ] && disEnable $idTouchPad
[ $1 == "touchscreen" ] && disEnable $idTouchScreen
